package constants

const (
    ElasticAddressEnv = "ES_ADDR"
    ElasticSniffEnv = "ES_SNIFF"
    EmailDurationEnv = "ESEC_EMAIL_DURATION"
    AggDurationEnv = "ESEC_AGG_DURATION"
    SlackHookEnv = "ESEC_SLACK_WEBHOOK"
    SendAddressEnv = "ESEC_SEND_ADDR"
    UrgentRegexEnv = "ESEC_URGENT_REGEX"
    EnvName = "ESEC_ENV_NAME"
    SSHAcceptedConnection = "Accepted SSH connection"
    SSHDisconnect = "SSH Disconnect"
    SSHFailedPass = "Failed SSH connection (invalid password)"
    SSHInvalidUser = "Failed SSH connection (invalid user)"
    AuthFailure = "Authentication Failure"
    NotSudoer = "Unauthorized sudo attempt"
    PrivEscalation = "Priviledge Escalation"
    FileIntegrityChange = "File Integrity Change"
    FailedFileAccess = "Failed File Access"
    AggregationEvent = "Aggregation Event"
    FileMetricSet = "audit.file"
    KernelMetricSet = "audit.kernel"
    UrgentRegexDefault = ".*prod.*"
    SendMailCommand = "mail"
)
